"use client";
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { ChevronUp, ChevronDown, ImagePlus } from "lucide-react";
import { FaDiscord, FaTelegram, FaTwitter,  } from "react-icons/fa";
import { TbWorld } from "react-icons/tb";

const TokenCreationForm = () => {
    const [isLessOptionsOpen, setIsLessOptionsOpen] = useState(false);
    const [solAmount, setSolAmount] = useState("0.00");

    const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (file) {
            // Handle image upload logic here
            console.log("Image uploaded:", file);
        }
    };

    return (
        <div className="min-h-screen p-4 md:p-8">
            <div className="max-w-3xl mx-auto">
                <div className="p-6 space-y-6 bg-card border-none">
                    {/* Image Upload */}
                    <div className="space-y-2">
                        <label
                            htmlFor="image-upload"
                            className="upload-area flex flex-col items-center justify-center h-32 rounded-lg cursor-pointer"
                        >
                            <ImagePlus className="w-8 h-8 text-primary mb-2" />
                            <span className="text-sm text-muted-foreground">Upload image</span>
                            <input
                                id="image-upload"
                                type="file"
                                accept="image/*"
                                onChange={handleImageUpload}
                                className="hidden"
                            />
                        </label>
                    </div>

                    {/* Name Field */}
                    <div className="space-y-2">
                        <label className="text-md text-muted-foreground">Name</label>
                        <Input
                            placeholder=""
                            className="form-input bg-input border-border text-foreground p-2 h-12"
                        />
                    </div>

                    {/* Ticker Field */}
                    <div className="space-y-2">
                        <label className="text-md text-muted-foreground">Ticker</label>
                        <Input
                            placeholder=""
                            className="form-input bg-input border-border text-foreground h-12 p-2"
                        />
                    </div>

                    {/* Description Field */}
                    <div className="space-y-2">
                        <label className="text-md text-muted-foreground">Description</label>
                        <Textarea
                            placeholder=""
                            className="form-input bg-input border-border text-foreground min-h-[80px] resize-none"
                        />
                    </div>

                    {/* Share Fees Section */}
                    <div className="space-y-4">
                        <div className="space-y-2">
                            <label className="text-md text-muted-foreground">
                                @ Share fees with a twitter account (optional)
                            </label>
                            <Input
                                placeholder=""
                                className="form-input bg-input border-border text-foreground h-12 p-2"
                            />
                        </div>
                        <p className="text-xs text-muted-foreground">
                            The twitter user above will be able to claim 90% of the fees generated by this coin, you will receive the remaining 10%
                        </p>
                    </div>

                    {/* Initial Buy Section */}
                    <div className="space-y-4">
                        <div className="space-y-2">
                            <label className="text-md text-muted-foreground">Initial Buy</label>
                            <div className="relative">
                                <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-primary font-medium">
                                    ◎
                                </span>
                                <Input
                                    value={solAmount}
                                    onChange={(e) => setSolAmount(e.target.value)}
                                    className="form-input bg-input border-border text-foreground pl-8 p-2 h-12"
                                    placeholder="0.00"
                                />
                                <span className="absolute right-3 top-1/2 transform -translate-y-1/2 text-muted-foreground ">
                                    SOL
                                </span>
                            </div>
                        </div>

                        <p className="text-xs text-muted-foreground">
                            Make sure to leave ~0.05 SOL for tx fees
                        </p>

                        <div className="flex items-center justify-between text-sm">
                            <div className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-primary"></span>
                                <span className="text-muted-foreground">0 SOL</span>
                            </div>
                            <span className="text-foreground">$0</span>
                        </div>

                        {/* Less Options */}
                        <Collapsible open={isLessOptionsOpen} onOpenChange={setIsLessOptionsOpen}>
                            <CollapsibleTrigger className="flex items-center gap-2 text-primary hover:text-primary/80 transition-colors">
                                {isLessOptionsOpen ? (
                                    <ChevronUp className="w-4 h-4" />
                                ) : (
                                    <ChevronDown className="w-4 h-4" />
                                )}
                                <span className="text-sm font-medium">Less options</span>
                            </CollapsibleTrigger>

                            <CollapsibleContent className="mt-4 space-y-4">
                                {/* Website Link */}
                                <div className="space-y-2">
                                    <label className="text-sm text-muted-foreground">Website link (optional)</label>
                                    <div className="relative flex-1">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                            <TbWorld></TbWorld>
                                        </span>
                                        <Input
                                            id="username"
                                            placeholder="Enter your website link"
                                            // onChange={(e) => setUsername(e.target.value)}
                                            className="pl-8 bg-input border-border h-12"
                                        />
                                    </div>
                                </div>

                                {/* Twitter/X Link */}
                                <div className="space-y-2">
                                    <label className="text-sm text-muted-foreground">Twitter/X link (optional)</label>
                                    <div className="relative flex-1">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                            <FaTwitter></FaTwitter>
                                        </span>
                                        <Input
                                            id="username"
                                            placeholder="Enter your twitter username"
                                            // onChange={(e) => setUsername(e.target.value)}
                                            className="pl-8 bg-input border-border h-12"
                                        />
                                    </div>
                                </div>
                                <div className="space-y-2">
                                    <label className="text-sm text-muted-foreground">Telegram link (optional)</label>
                                    <div className="relative flex-1">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                            <FaTelegram></FaTelegram></span>
                                        <Input
                                            id="username"
                                            placeholder="Enter your telegram username"
                                            // onChange={(e) => setUsername(e.target.value)}
                                            className="pl-8 bg-input border-border h-12"
                                        />
                                    </div>
                                </div>

                                <div className="space-y-2">
                                    <label className="text-sm text-muted-foreground">Discord link (optional)</label>
                                    {/* <Input 
                    placeholder=""
                    className="form-input bg-input border-border text-foreground"
                  /> */}
                                    <div className="relative flex-1">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                                            <FaDiscord></FaDiscord></span>
                                        <Input
                                            id="username"
                                            placeholder="Enter your Discord username"
                                            // onChange={(e) => setUsername(e.target.value)}
                                            className="pl-8 bg-input border-border h-12"
                                        />
                                    </div>
                                </div>
                            </CollapsibleContent>
                        </Collapsible>
                    </div>

                    {/* Verify Button */}
                    <Button className="w-full gradient-button text-primary-foreground font-medium py-3 rounded-lg">
                        𝕏 Verify with X
                    </Button>
                </div>
            </div>
        </div>
    );
};

export default TokenCreationForm;