import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import { TrendingSidebar } from "@/components/TrendingSidebar";
import WagmiProviders from "@/components/walletConnector/WalletProvider";
import StoreProvider from "@/redux/reduxProvider";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WagmiProviders>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <Header />

              <div className="flex pt-16 min-h-screen max-w-3xl m-auto">
                <main className="w-full mt-10">
                    <Toaster position="top-center" />

                    {children}
                  </main>

                
              
              </div>
            </body>
          </StoreProvider>
        </ThemeProvider>
      </WagmiProviders>
    </html>
  );
}